# Use the official Caddy image as the base image
FROM caddy:2.8.4


# Set permissions for non root user in directories we will need
RUN mkdir -p /data && chown -R 1000:1000 /data


# Copy the Caddyfile from the host to the container
COPY Caddyfile /etc/caddy/Caddyfile